### PR TITLE
Fixed Issue 870, 871

### PR DESCRIPTION
**Pull request by ValDekh**
## Summary of issue

#870 and #871

## Summary of change

Fix all issues

### CODE REVIEW

**Review by BohdanBybliv — APPROVED** [review]

**Review by KateYatsiuk — APPROVED** [review]

**Comment by Adeodonne** [comment]
image
Error labels is doubled

**Comment by ValDekh** [comment]
> image Error labels is doubled

Done

**Comment by Oleh-Kril** [comment]
Screenshot 2023-12-08 at 10 06 12 AM

- Modal form isn't centred vertically
- Somehow I can submit form without a message and/or email (it just closes)

**Review by Oleh-Kril — CHANGES_REQUESTED** [review]
Fix comments.

And please don't combine several bugs in 1 pull request because #871 is fixed but we can't merge if because of #870 is present in this pull request

**Comment by ValDekh** [comment]
> Fix comments.
> 
> And please don't combine several bugs in 1 pull request because #871 is fixed but we can't merge if because of #870 is present in this pull request

This has been fixed by BohdanBybliv. And then I've merged his branch to this.

**Review by Oleh-Kril — APPROVED** [review]
The problems with contact us modal are gone

**Pull request merged**
